import { Link } from "wouter";
import { ArrowLeft, FileText, Scale } from "lucide-react";
import { motion } from "framer-motion";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold mb-4 text-foreground">{title}</h2>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
        {children}
      </div>
    </section>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />

      <main className="flex-1 container mx-auto px-4 sm:px-6 lg:px-8 py-12 max-w-3xl">
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors mb-8">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Home
          </Link>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center">
              <Scale className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">Terms of Service</h1>
              <p className="text-sm text-muted-foreground mt-0.5">Last updated: March 2025</p>
            </div>
          </div>

          <p className="text-muted-foreground mb-10 leading-relaxed">
            These Terms of Service govern your use of ThreatLegion ("the Service"). By accessing or using ThreatLegion, you agree to be bound by these terms. Please read them carefully.
          </p>

          <Section title="1. Acceptance of Terms">
            <p>By using ThreatLegion, you agree to these Terms of Service and our Privacy Policy. If you do not agree to these terms, you may not use the Service. We may update these terms at any time; continued use of the Service after changes constitutes acceptance.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>ThreatLegion is an AI-powered security scanning tool that analyzes GitHub repositories for potential security vulnerabilities. The Service uses large language models (Claude AI by Anthropic) to review source code and generate vulnerability reports.</p>
            <p>The Service is provided for informational purposes only. Scan results are not a guarantee of security and should not be relied upon as a complete security assessment.</p>
          </Section>

          <Section title="3. Limitation of Liability — Security Disclaimer">
            <p className="text-yellow-400/80 font-medium">This section is important. Please read it carefully.</p>
            <p>ThreatLegion's scan results are generated by AI and are inherently imperfect. By using the Service, you acknowledge and agree that:</p>
            <ul className="list-disc list-inside space-y-2 pl-2">
              <li>The scanner <strong className="text-foreground">may miss vulnerabilities</strong>, including critical security flaws.</li>
              <li>A "clean" scan report does not mean your code is secure. New vulnerabilities may be introduced after a scan.</li>
              <li>ThreatLegion is <strong className="text-foreground">not a substitute</strong> for professional security audits, penetration testing, or manual code review.</li>
              <li>ThreatLegion and its operators are <strong className="text-foreground">not liable</strong> for any security breach, data loss, or damages arising from vulnerabilities present in or introduced to your codebase, whether detected or undetected by the Service.</li>
            </ul>
          </Section>

          <Section title="4. Authorized Repository Access">
            <p>You may only scan repositories for which you have explicit authorization — specifically, repositories you own or where you have been granted collaborator access. Scanning repositories you do not have authorization to access may violate applicable laws, including the Computer Fraud and Abuse Act (CFAA) and similar legislation.</p>
            <p>By submitting a repository URL, you represent and warrant that you have the right to authorize a security scan of that repository. ThreatLegion verifies ownership via your connected GitHub account.</p>
          </Section>

          <Section title="5. User Accounts">
            <p>ThreatLegion uses Replit authentication. You are responsible for maintaining the security of your account. You agree to notify us immediately of any unauthorized use of your account. We are not liable for any loss or damage from your failure to comply with this security obligation.</p>
          </Section>

          <Section title="6. Acceptable Use">
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 pl-2">
              <li>Scan repositories you do not have authorization to access.</li>
              <li>Attempt to reverse engineer, decompile, or extract the underlying AI models or systems.</li>
              <li>Use the Service for any illegal, harmful, or abusive purpose.</li>
              <li>Attempt to circumvent rate limits, access controls, or other protective measures.</li>
              <li>Resell or commercialize scan results without our written permission.</li>
            </ul>
          </Section>

          <Section title="7. Intellectual Property">
            <p>ThreatLegion and its content, features, and functionality are owned by its operators. You retain ownership of your repositories and code. By submitting a repository for scanning, you grant ThreatLegion a limited, temporary license to access and analyze the code solely for the purpose of generating the security report.</p>
            <p>We do not store the content of your repositories beyond what is necessary to generate your scan report. See our Privacy Policy for details on data retention.</p>
          </Section>

          <Section title="8. Subscription and Payment">
            <p>ThreatLegion offers a free tier and a paid Pro tier ($10/month). Subscription changes (upgrades and downgrades) take effect immediately. We do not offer refunds for partial billing periods. All prices are in US dollars and subject to change with notice.</p>
          </Section>

          <Section title="9. Termination">
            <p>We reserve the right to suspend or terminate your access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately.</p>
          </Section>

          <Section title="10. Disclaimer of Warranties">
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.</p>
          </Section>

          <Section title="11. Governing Law">
            <p>These Terms are governed by the laws of the jurisdiction in which ThreatLegion operates, without regard to its conflict of law provisions. Any disputes arising from these Terms or your use of the Service shall be resolved through binding arbitration or in the applicable courts.</p>
          </Section>

          <Section title="12. Contact">
            <p>If you have any questions about these Terms, you may contact us through the Replit platform where ThreatLegion is hosted.</p>
          </Section>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
